apiVersion: v1
kind: Service
metadata:
  name: {{ include "control.fullname" . }}
  labels:
    {{- include "control.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: control
      protocol: TCP
      name: control
  selector:
    {{- include "control.selectorLabels" . | nindent 4 }}
