apiVersion: v1
kind: Service
metadata:
  name: {{ include "payments.fullname" . }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: payments
      protocol: TCP
      name: payments
  selector:
    {{- include "payments.selectorLabels" . | nindent 4 }}
