apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-prod
  name: letsencrypt-prod
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    name: r53-letsencrypt-prod
  name: r53-letsencrypt-prod
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: r53-letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            {{- range .Values.dnsZones }}
            - {{.}}
            {{- end }}
        dns01:
          route53:
            region: us-east-1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "default-certificates"
spec:
  secretName: "default-certificates"
  dnsNames:
    {{- range .Values.defaultCertificateRequest }}
    - "{{.}}"
    {{- end }}
  issuerRef:
    name: r53-letsencrypt-prod
    kind: ClusterIssuer