apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ledger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ledger.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ledger.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-ui"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["numary", "ui"]
          ports:
            - name: ledger-ui
              containerPort: 3078
              protocol: TCP
          env:
            - name: NUMARY_UI_HTTP_BIND_ADDRESS
              value: {{ .Values.ledger.UIHttpBindAddr }}
          livenessProbe:
            httpGet:
              path: /
              port: ledger-ui
          readinessProbe:
            httpGet:
              path: /
              port: ledger-ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NUMARY_STORAGE_DRIVER
              value: {{ .Values.ledger.storage.driver }}
            - name: NUMARY_STORAGE_POSTGRES_CONN_STRING
              value: {{ .Values.ledger.storage.connString }}
            - name: NUMARY_SERVER_HTTP_BIND_ADDRESS
              value: {{ .Values.ledger.httpBindAddr }}
          ports:
            - name: ledger
              containerPort: 3068
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ledger
          readinessProbe:
            httpGet:
              path: /
              port: ledger
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
