apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ledger
      protocol: TCP
      name: ledger
  selector:
    {{- include "ledger.selectorLabels" . | nindent 4 }}
