apiVersion: v2
name: search
description: A Helm chart for Kubernetes
home: "https://formance.com"
sources:
  - "https://github.com/numary/control"
maintainers:
  - name: "Formance Team"
    email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"
type: application
version: 1.0.0
appVersion: "v0.1.0"
