name: "release charts"

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add Helm repo
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo add jetstack https://charts.jetstack.io
          helm repo add formance https://helm.formance.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts
          config: cr.yaml
          charts_repo_url: "https://helm.formance.com"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"